spring:
    application:
        name: bookmanager
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: user
        password: password
    h2:
        console:
            enabled: true
